server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_route1  #路由1          #路由的id，没有固定规则但必须唯一，建议配合服务名
          #uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**    #断言，路径向匹配的进行路由
            - After=2024-11-18T21:37:00.633995400+08:00[GMT+08:00]  # 在这个时间之后才能访问  Before在之前 Between之间
            #- Cookie=username,hxy # 请求中要有Cookie并且值为hxy才能访问
            #- Header=token,big   # 请求头中要有token属性并且值为big才能访问
            #- Host=**.hxy.com     # 请求中要有Host属性并且值的后缀为hxy.com才能访问
            #- Query=username, \d+  # 请求路径中要有param参数并且值必须是整数
            #- RemoteAddr=192.168.235.91  # 请求来源IP地址是192.168.235.91才能访问
            #- Method=GET,POST # 请求方式必须是GET或POST才能访问
            #- My=diamond
#            - name: My
#              args:
#                userType: diamond

        - id: pay_route2  #路由2         #路由的id，没有固定规则但必须唯一，建议配合服务名
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**  #断言，路径向匹配的进行路由

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
            #- Path=/gateway/filter/**
            #- Path=/XYZ/abc/{segment}        # {segment}的内容会被SetPath取代
          filters:
            #- RedirectTo=302,https://www.bilibili.com    # 访问localhost:9527/pay/gateway/filter 会跳转到b站，并指定跳转的状态码为302
            #- SetPath=/pay/gateway/{segment}
            #- PrefixPath=/pay   # http://localhost:9527/pay/gateway/filter   设设置请求路径前缀 可以隐藏服务的真是路径
            - AddRequestHeader=X-Request-hxy1,yellow1  # 请求头kv，若一头含有多参则重写一行设置
            - My=hxy
#            - AddRequestHeader=X-Request-hxy2,yellow2
#            - RemoveRequestHeader=sec-fetch-site       # 删除请求头中的某个参数
#            - SetRequestHeader=sec-fetch-mode,updatebyhxy       # 修改请求头中的某个参数
#            - AddRequestParameter=customerId,1557        # 新增请求参数Parameter：k ，v  如果请求路径中传递了customerId的值，则路径中的值会覆盖配置文件中的值
#            - RemoveRequestParameter=customerName      # 删除url请求参数customerName，传递过来也是null
#            - AddResponseHeader=X-Request-hxy,YellowResponse  # 添加响应头参数X-Request-hxy 值为YellowResponse
#            - SetResponseHeader=Date,2099-11-11        # 修改响应头参数Date的值
#            - RemoveResponseHeader=Content-Type        # 删除响应头参数Content-Type


